name = 'Simpla'
license = 'MIT'
licenselink = 'https://github.com/aziyan99/gohugo-theme-simpla/LICENSE'
description = ''
homepage = 'https://github.com/aziyan99/gohugo-theme-simpla'
demosite = 'https://aziyan99.github.io/gohugo-theme-simpla'

tags = ['blog', 'simple']
categories = ['blog']

[author]
  name = 'Raja Azian'
  homepage = 'https://github.com/aziyan99'

[original]
  author = 'Michael Henriksen'
  homepage = 'https://michenriksen.com/'
  repo = 'https://github.com/michenriksen/hugo-theme-til'
